spec:
  scope: Namespaced
  group: drowzee.challengr.io
  names:
    kind: SleepSchedule
    plural: sleepschedules
    singular: sleepschedule
    shortNames:
      - ss
  versions:
    - name: v1beta1
      deprecated: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                hosts:
                  type: array
                  items:
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                      type:
                        type: string
                      reason:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
            spec:
              type: object
              required:
                - sleepTime
                - timezone
              properties:
                deployments:
                  type: array
                  description: The deployments that will be slept/woken.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                statefulsets:
                  type: array
                  description: The statefulsets that will be slept/woken.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                cronjobs:
                  type: array
                  description: The cronjobs that will be suspended/resumed.
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                ingressName:
                  type: string
                  description: The ingress that will be slept/woken.
                sleepTime:
                  type: string
                  description: "The time that the deployment will start sleeping(format: HH:MMam/pm)"
                timezone:
                  type: string
                  description: The timezone that the input times are based in
                wakeTime:
                  type: string
                  description: "The time that the deployment will wake up (format: HH:MMam/pm)"
      storage: true
      additionalPrinterColumns:
        - name: SleepTime
          type: string
          description: Starts Sleeping
          jsonPath: .spec.sleepTime
        - name: WakeTime
          type: string
          description: Wakes Up
          jsonPath: .spec.wakeTime
        - name: Timezone
          type: string
          description: Timezone
          jsonPath: .spec.timezone
        - name: Deployments
          type: string
          description: Deployments
          jsonPath: .spec.deployments[*].name
        - name: StatefulSets
          type: string
          description: StatefulSets
          jsonPath: .spec.statefulsets[*].name
        - name: CronJobs
          type: string
          description: CronJobs
          jsonPath: .spec.cronjobs[*].name
        - name: Sleeping?
          type: string
          description: Current Status
          jsonPath: .status.conditions[?(@.type == "Sleeping")].status
        - name: Transitioning?
          type: string
          description: Status Change In Progress
          jsonPath: .status.conditions[?(@.type == "Transitioning")].status
        - name: ManualOverride?
          type: string
          description: Status overridden by user
          jsonPath: .status.conditions[?(@.type == "ManualOverride")].status
      served: true
      deprecationWarning:
metadata:
  name: sleepschedules.drowzee.challengr.io
  labels:
    k8s-app: drowzee
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
